### ISSUE TITLE
HTTP Service überarbeiten (Angular 5 HTTP Client verwenden)

### ISSUE THREAD

**Issue by tschuegge** [PROFFIX-NET/restapi-angular-library#6]
HTTP-Service überarbeiten, dass nicht mehr @angular/http sondern der neue Angular 5 HTTP-Client (@angular/common/http) verwendet wird.

**Comment by kreavivity** [comment]
https://github.com/PROFFIX-NET/restapi-angular-library/commit/2d6123ae368aa0a8c80027ccc8dc0774ae2f5eb5
